
version: '3.8'

services:
  accounts:
    image: "shubhamthakur614/accounts:v1"
    container_name: accountsMs
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "eazybank"

  loans:
      image: "shubhamthakur614/loans:v1"
      container_name: loansMs
      ports:
        - "8090:8090"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - "eazybank"

  cards:
      image: "shubhamthakur614/cards:v1"
      container_name: cardsMs
      ports:
        - "9000:9000"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - "eazybank"

networks:
  eazybank:
    driver: "bridge"

