server:
  port: 9000

spring:
  application:
    name: "cards"
  profiles:
    active: "qa"

  # SQL Configuration
  datasource:
    url: jdbc:mysql://localhost:3309/cardsdb?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # Hibernate-specific properties to show and format SQL
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://localhost:8071/"

  # To use cloud bus and git hook, use this property
  # rabbitmq:
  #   host: "localhost"
  #   port: 5672
  #   username: "guest"
  #   password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
