
version: '3.8'

services:
  rabbit:
    image: "rabbitmq:3.12-management"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: "rabitmq-diagnostics check_port_connectivity"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "shubhamthakur614/configserver:v2"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

    extends:
      file: common-config.yml
      service: microservice-base-config


  accounts:
    image: "shubhamthakur614/accounts:v2"
    container_name: accounts-ms
    ports:
      - "8080:8080"

    environment:
      SPRING_APP_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
      image: "shubhamthakur614/loans:v2"
      container_name: loans-ms
      ports:
        - "8090:8090"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - "eazybank"
#      environment:
#        SPRING_APP_NAME: "loans"
#        SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
#        SPRING_PROFILES_ACTIVE: default

  cards:
      image: "shubhamthakur614/cards:v2"
      container_name: cards-ms
      ports:
        - "9000:9000"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - "eazybank"
#      environment:
#        SPRING_APP_NAME: "cards"
#        SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
#        SPRING_PROFILES_ACTIVE: default

networks:
  eazybank:
    driver: "bridge"

